# Generated by Django 4.1.7 on 2023-02-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('jobtitle', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('gitlink', models.CharField(max_length=122)),
                ('linkd', models.CharField(max_length=122)),
                ('number', models.IntegerField()),
                ('profile', models.CharField(max_length=322)),
                ('skill1', models.CharField(max_length=122)),
                ('skill2', models.CharField(max_length=122)),
                ('skill3', models.CharField(max_length=122)),
                ('technichal1', models.CharField(max_length=122)),
                ('technichal2', models.CharField(max_length=122)),
                ('technichal3', models.CharField(max_length=122)),
                ('technichal4', models.CharField(max_length=122)),
                ('technichal5', models.CharField(max_length=122)),
                ('companyname', models.CharField(max_length=122)),
                ('jobtype', models.CharField(max_length=122)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('uname', models.CharField(max_length=122)),
                ('dptname', models.CharField(max_length=122)),
                ('cgpa', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
